# Local testing docker-compose with locally built images

services:
  stories-service:
    build:
      context: .
      dockerfile: Dockerfile.stories
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/app/config/production.yaml
    depends_on:
      - postgres
      - minio
      - redis
    networks:
      - app-network
    restart: unless-stopped

  ephemeral-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - CONFIG_PATH=/app/config/production.yaml
    depends_on:
      - postgres
      - minio
      - redis
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: stories_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2024-09-13T20-26-02Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  app-network:
    driver: bridge
