env: "dev"
pgsql:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password123"
  dbname: "stories_db"
  sslmode: "disable"
http_server:
  address: "localhost:8080"
jwt_secret: "not_so_secret_key"