// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/feed": {
            "get": {
                "tags": [
                    "stories"
                ],
                "summary": "Get stories feed",
                "responses": {}
            }
        },
        "/stories": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "stories"
                ],
                "summary": "Create a new story",
                "parameters": [
                    {
                        "description": "Story content",
                        "name": "story",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.StoryPostRequest"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "types.StoryPostRequest": {
            "type": "object",
            "required": [
                "audience_user_ids",
                "visibility"
            ],
            "properties": {
                "audience_user_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "media_key": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Stories Service API",
	Description:      "A simple stories service API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
