basePath: /
definitions:
  response.Response:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  types.StoryPostRequest:
    properties:
      audience_user_ids:
        items:
          type: string
        type: array
      media_key:
        type: string
      text:
        type: string
      visibility:
        type: string
    required:
    - audience_user_ids
    - visibility
    type: object
  users.SignInRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  users.SignUpRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
info:
  contact: {}
  description: A simple stories service API
  title: Stories Service API
  version: "1.0"
paths:
  /feed:
    get:
      responses: {}
      summary: Get stories feed
      tags:
      - stories
  /login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return JWT token
      parameters:
      - description: User login details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/users.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User authenticated successfully with token
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
      summary: Authenticate a user
      tags:
      - users
  /signup:
    post:
      consumes:
      - application/json
      description: Register a new user account
      parameters:
      - description: User registration details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/users.SignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Register a new user
      tags:
      - users
  /stories:
    post:
      consumes:
      - application/json
      description: Create a new story with authentication required
      parameters:
      - description: Story content
        in: body
        name: story
        required: true
        schema:
          $ref: '#/definitions/types.StoryPostRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Story created successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Create a new story
      tags:
      - stories
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
